### ISSUE TITLE
Text area scroll not working

### ISSUE THREAD

**Issue by SalvadorDuran** [smackgg/vue-scroll-lock#2]
The text-area tag inside vue-scroll-lock component can't be scrollable

**Comment by smackgg** [comment]
oh, it's a bug~~

**Comment by smackgg** [comment]
Oh, it's a bug~~
Do you have a good idea?
@SalvadorDuran

**Comment by smackgg** [comment]
Fixed on https://github.com/smackgg/vue-scroll-lock/pull/3 @SalvadorDuran

**Comment by SalvadorDuran** [comment]
@smackgg could you upgrade the NPM package? Could I translate the documentation to english?

you can close the issue
Thanks!

**Comment by smackgg** [comment]
Yes, you can translate the documentation to english if you have free time. I will upgrade the npm package tomorrow.

**Comment by smackgg** [comment]
@SalvadorDuran What about the documentation?😁
